# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if .Values.shippingService.create }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shippingservice
spec:
  serviceName: shippingservice
  selector:
    matchLabels:
      app: shippingservice
      version: "1"
  replicas: 3
  template:
    metadata:
      labels:
        app: shippingservice
        version: "1"
    spec:
      containers:
      - name: server
        image: {{ .Values.images.repository }}/{{ .Values.shippingService.name }}:{{ .Values.images.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        #- name: DISABLE_STATS
        #  value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: JAEGER_SERVICE_ADDR
          value: "jaeger-collector.observe.svc.cluster.local:14268/api/traces"
        - name: SERVICE_NAME
          value: "shippingservice"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
    version: "1"
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
{{- end }}